const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Load environment variables from .env file
dotenv.config();

// Always write to both files to ensure ANY build configuration picks up the values
// This supports dynamic stages (dev, uat, prod) without needing specific angular.json replacements
const targetPathDefault = path.join(__dirname, '../src/environments/environment.ts');
const targetPathProd = path.join(__dirname, '../src/environments/environment.prod.ts');

const apiBaseUrl = process.env.API_BASE_URL ? process.env.API_BASE_URL.trim().replace(/\/$/, '') : '';
console.log('Resolved API_BASE_URL:', apiBaseUrl);

const envConfigFile = `// Auto-generated by set-env.js during CI/CD
export const environment = {
    // We set production: true to ensure Angular enables production mode (optimizations)
    // regardless of the specific stage (dev, uat, prod) being deployed.
    production: true, 
    cognito: {
        userPoolId: '${process.env.COGNITO_USER_POOL_ID}',
        userPoolWebClientId: '${process.env.COGNITO_WEB_CLIENT_ID}',
        domain: '${process.env.COGNITO_DOMAIN ? process.env.COGNITO_DOMAIN.replace(/^https?:\/\//, '') : ''}',
        redirectSignIn: '${process.env.COGNITO_REDIRECT_SIGNIN}',
        redirectSignOut: '${process.env.COGNITO_REDIRECT_SIGNOUT}',
    },
    api: {
        baseUrl: '${apiBaseUrl}',
        endpoints: {
            profile: '/profile',
            sampleEmail: '/sample-email',
            subscribe: '/subscribe'
        }
    },
    vapidPublicKey: '${process.env.VAPID_PUBLIC_KEY}',
    razorpay: {
        keyId: '${process.env.RAZORPAY_KEY_ID || 'rzp_test_SC6SfzckFW4xe0'}'
    }
};
`;

console.log(`Generating environment files...`);

function writeFileSafe(filePath, content) {
    try {
        const dir = path.dirname(filePath);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
        fs.writeFileSync(filePath, content);
        console.log(`Updated ${filePath}`);
    } catch (err) {
        console.error(`Error writing to ${filePath}:`, err);
        process.exit(1);
    }
}

// Write to environment.ts
writeFileSafe(targetPathDefault, envConfigFile);

// Write to environment.prod.ts
writeFileSafe(targetPathProd, envConfigFile);
