// Auto-generated by set-env.js during CI/CD
export const environment = {
    // We set production: true to ensure Angular enables production mode (optimizations)
    // regardless of the specific stage (dev, uat, prod) being deployed.
    production: true, 
    cognito: {
        userPoolId: 'ap-south-1_g6cAch9nf',
        userPoolWebClientId: '5bjct26m4mgt914kp0rmjfaad4',
        domain: 'thirukkural-app-612850243659.auth.ap-south-1.amazoncognito.com',
        redirectSignIn: 'https://thirukkural.krss.online/callback',
        redirectSignOut: 'https://thirukkural.krss.online/',
    },
    api: {
        baseUrl: 'https://api.krss.online',
        endpoints: {
            profile: '/profile',
            sampleEmail: '/sample-email',
            subscribe: '/subscribe'
        }
    },
    vapidPublicKey: 'undefined'
};
