// Development environment configuration
// For production deployment, environment.prod.ts is auto-generated by scripts/set-env.js

export const environment = {
    production: false,
    cognito: {
        userPoolId: 'YOUR_USER_POOL_ID',
        userPoolWebClientId: 'YOUR_USER_POOL_CLIENT_ID',
        domain: 'YOUR_COGNITO_DOMAIN_PREFIX.auth.ap-south-1.amazoncognito.com',
        redirectSignIn: 'http://localhost:4200/callback',
        redirectSignOut: 'http://localhost:4200/',
    },
    api: {
        baseUrl: 'YOUR_API_GATEWAY_URL', // e.g., https://api.example.com
        endpoints: {
            profile: '/profile',
            sampleEmail: '/sample-email',
            subscribe: '/subscribe'
        }
    },
    // Generate VAPID keys using: npx web-push generate-vapid-keys
    vapidPublicKey: 'YOUR_VAPID_PUBLIC_KEY'
};
