export const KURAL_FILTER_MAPPING = {
  "pal": {
    "Virtue": "அறத்துப்பால்",
    "Wealth": "பொருட்பால்",
    "Love": "காமத்துப்பால்"
  },
  "iyal": {
    "Prologue": "பாயிரவியல்",
    "Domestic Virtue": "இல்லறவியல்",
    "Ascetic Virtue": "துறவறவியல்",
    "Fate": "ஊழியல்",
    "Royalty": "அரசியல்",
    "Minister of State": "அமைச்சியல்",
    "The Essentials of a State": "அரணியல்",
    "Way of Making Wealth": "கூழியல்",
    "The Excellence of an Army": "படையில்",
    "Friendship": "நட்பியல்",
    "Miscellaneous": "குடியியல்",
    "The Pre-marital love": "களவியல்",
    "The Post-marital love": "கற்பியல்"
  },
  "adikaram": {
    "The Praise of God": "கடவுள் வாழ்த்து",
    "The Blessing of Rain": "வான்சிறப்பு",
    "The Greatness of Ascetics": "நீத்தார் பெருமை",
    "Assertion of the Strength of Virtue": "அறன் வலியுறுத்தல்",
    "Domestic Life": "இல்வாழ்க்கை",
    "The Worth of a Wife": "வாழ்க்கைத் துணைநலம்",
    "The Wealth of Children": "மக்கட்பேறு",
    "The Possession of Love": "அன்புடைமை",
    "Hospitality": "விருந்தோம்பல்",
    "The Utterance of Pleasant Words": "இனியவை கூறல்",
    "Gratitude": "செய்ந்நன்றியறிதல்",
    "Impartiality": "நடுவு நிலைமை",
    "The Possession of Self-restraint": "அடக்கம் உடைமை",
    "The Possession of Decorum": "ஒழுக்கம் உடைமை",
    "Not coveting another\"s Wife": "பிறனில் விழையாமை",
    "The Possession of Patience, Forbearance": "பொறையுடைமை",
    "Not Envying": "அழுக்காறாமை",
    "Not Coveting": "வெஃகாமை",
    "Not Backbiting": "புறங்கூறாமை",
    "Against Vain Speaking": "பயனில சொல்லாமை",
    "Dread of Evil Deeds": "தீவினையச்சம்",
    "Duty to Society": "ஒப்புரவறிதல்",
    "Giving": "ஈகை",
    "Renown": "புகழ்",
    "Compassion": "அருளுடைமை",
    "Abstinence from Flesh": "புலால் மறுத்தல்",
    "Penance": "தவம்",
    "Imposture": "கூடா ஒழுக்கம்",
    "The Absence of Fraud": "கள்ளாமை",
    "Veracity": "வாய்மை",
    "Restraining Anger": "வெகுளாமை",
    "Not doing Evil": "இன்னா செய்யாமை",
    "Not killing": "கொல்லாமை",
    "Instability": "நிலையாமை",
    "Renunciation": "துறவு",
    "Truth-Conciousness": "மெய்யுணர்தல்",
    "Curbing of Desire": "அவா அறுத்தல்",
    "Fate": "ஊழ்",
    "The Greatness of a King": "இறைமாட்சி",
    "Learning": "கல்வி",
    "Ignorance": "புல்லறிவாண்மை",
    "Hearing": "கேள்வி",
    "The Possession of Knowledge": "அறிவுடைமை",
    "The Correction of Faults": "குற்றங்கடிதல்",
    "Seeking the Aid of Great Men": "பெரியாரைத் துணைக்கோடல்",
    "Avoiding mean Associations": "சிற்றினம் சேராமை",
    "Acting after due Consideration": "தெரிந்து செயல்வகை",
    "The Knowledge of Power": "வலியறிதல்",
    "Knowing the fitting Time": "காலமறிதல்",
    "Knowing the Place": "இடனறிதல்",
    "Selection and Confidence": "தெரிந்து தெளிதல்",
    "Selection and Employment": "தெரிந்து வினையாடல்",
    "Cherishing Kinsmen": "சுற்றந் தழால்",
    "Unforgetfulness": "பொச்சாவாமை",
    "The Right Sceptre": "செங்கோன்மை",
    "The Cruel Sceptre": "கொடுங்கோன்மை",
    "Absence of Terrorism": "வெருவந்த செய்யாமை",
    "Benignity": "கண்ணோட்டம்",
    "Detectives": "ஒற்றாடல்",
    "Energy": "ஊக்கம் உடைமை",
    "Unsluggishness": "மடி இன்மை",
    "Manly Effort": "ஆள்வினை உடைமை",
    "Hopefulness in Trouble": "இடுக்கண் அழியாமை",
    "The Office of Minister of state": "அமைச்சு",
    "Power of Speech": "சொல்வன்மை",
    "Purity in Action": "வினைத் தூய்மை",
    "Power in Action": "வினைத்திட்பம்",
    "Modes of Action": "வினை செயல்வகை",
    "The Envoy": "தூது",
    "Conduct in the Presence of the King": "மன்னரைச் சேர்ந்து ஒழுகல்",
    "The Knowledge of Indications": "குறிப்பறிதல்",
    "The Knowledge of the Council Chamber": "அவை அறிதல்",
    "Not to dread the Council": "அவை அஞ்சாமை",
    "The Land": "நாடு",
    "The Fortification": "அரண்",
    "Way of Accumulating Wealth": "பொருள் செயல்வகை",
    "The Excellence of an Army": "படை மாட்சி",
    "Military Spirit": "படைச் செருக்கு",
    "Friendship": "நட்பு",
    "Investigation in forming Friendships": "நட்பாராய்தல்",
    "Familiarity": "பழைமை",
    "Evil Friendship": "தீ நட்பு",
    "Unreal Friendship": "கூடா நட்பு",
    "Folly": "பேதைமை",
    "Hostility": "இகல்",
    "The Might of Hatred": "பகை மாட்சி",
    "Knowing the Quality of Hate": "பகைத்திறம் தெரிதல்",
    "Enmity within": "உட்பகை",
    "Not Offending the Great": "பெரியாரைப் பிழையாமை",
    "Being led by Women": "பெண்வழிச் சேறல்",
    "Wanton Women": "வரைவின் மகளிர்",
    "Not Drinking Palm-Wine": "கள்ளுண்ணாமை",
    "Gambling": "சூது",
    "Medicine": "மருந்து",
    "Nobility": "குடிமை",
    "Honour": "மானம்",
    "Greatness": "பெருமை",
    "Perfectness": "சான்றாண்மை",
    "Courtesy": "பண்புடைமை",
    "Wealth without Benefaction": "நன்றியில் செல்வம்",
    "Shame": "நாணுடைமை",
    "The Way of Maintaining the Family": "குடிசெயல் வகை",
    "Farming": "உழவு",
    "Poverty": "நல்குரவு",
    "Mendicancy": "இரவு",
    "The Dread of Mendicancy": "இரவச்சம்",
    "Baseness": "கயமை",
    "The Pre-marital love": "தகை அணங்குறுத்தல்",
    "Recognition of the Signs ": "குறிப்பறிதல்",
    "Rejoicing in the Embrace": "புணர்ச்சி மகிழ்தல்",
    "The Praise of her Beauty": "நலம் புனைந்து உரைத்தல்",
    "Declaration of Love\"s special Excellence": "காதற் சிறப்புரைத்தல்",
    "The Abandonment of Reserve": "நாணுத் துறவுரைத்தல்",
    "The Announcement of the Rumour": "அலர் அறிவுறுத்தல்",
    "Separation unendurable": "பிரிவு ஆற்றாமை",
    "Complainings": "படர்மெலிந் திரங்கல்",
    "Eyes consumed with Grief": "கண் விதுப்பழிதல்",
    "The Pallid Hue": "பசப்புறு பருவரல்",
    "The Solitary Anguish": "தனிப்படர் மிகுதி",
    "Sad Memories": "நினைந்தவர் புலம்பல்",
    "The Visions of the Night": "கனவுநிலை உரைத்தல்",
    "Lamentations at Eventide": "பொழுதுகண்டு இரங்கல்",
    "Wasting Away": "உறுப்புநலன் அழிதல்",
    "Soliloquy": "நெஞ்சொடு கிளத்தல்",
    "Reserve Overcome": "நிறையழிதல்",
    "Mutual Desire": "அவர்வயின் விதும்பல்",
    "The Reading of the Signs": "குறிப்பறிவுறுத்தல்",
    "Desire for Reunion": "புணர்ச்சி விதும்பல்",
    "Expostulation with Oneself": "நெஞ்சொடு புலத்தல்",
    "Pouting": "புலவி",
    "Feigned Anger": "புலவி நுணுக்கம்",
    "The Pleasures of Temporary Variance": "ஊடலுவகை"
  }
};